---
name: Carp-Diagnostics
version: 0.05.3
author:
  - 'Khemir Nadim ibn Hamouda. <nadim@khemir.net>'
abstract: Carp with a diagnostic message
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  IO::String: 0
  Pod::Text: 0
  Readonly: 0
  Sub::Exporter: 0
  Term::Size: 0.2
  Test::Block: 0
  Test::Exception: 0
  Test::NoWarnings: 0
  Test::Warn: 0
provides:
  Carp::Diagnostics:
    file: lib/Carp/Diagnostics.pm
    version: 0.05
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
